Assignment-1 review
adyashree-mahapatra/AWS_Sagemaker_Assignments pull request #2
Opened 2021-04-26 16:11 UTC by adyashree-mahapatra

2021-04-27 06:08 UTC, leninkumar-sv-tiger requested changes

2021-04-27 06:08 UTC, leninkumar-sv-tiger commented on Assignment-1/app.py
> +    AWS_S3_REGION_NAME='ap-south-1'
Please refer regions from ENV variables.

2021-04-27 06:08 UTC, leninkumar-sv-tiger commented on Assignment-1/app.py
> +    AWS_STORAGE_BUCKET_NAME='1668-mybucket'
Please use boto3 to list buckets and select from the list

2021-04-27 06:08 UTC, leninkumar-sv-tiger commented on README.md
> +# **Assignment-1**
Please paste image containing daily cost incurred grouped by Service and Tag

2021-04-28 07:45 UTC, adyashree-mahapatra commented on README.md
> +# **Assignment-1**
I have pasted the images of daily cost incurred group by service and tags in the README.md.

2021-04-28 07:46 UTC, adyashree-mahapatra commented on Assignment-1/app.py
> +    AWS_S3_REGION_NAME='ap-south-1'
Removed the region variable mentioned in the code

2021-04-28 07:47 UTC, adyashree-mahapatra commented on Assignment-1/app.py
> +    AWS_STORAGE_BUCKET_NAME='1668-mybucket'
I have updated the code to take bucket name from the list generated using boto3.

2021-04-29 03:05 UTC, leninkumar-sv-tiger approved these changes
Thanks for making the changes. Please merge to main

2021-04-29 06:51 UTC, merged